title: Eureka
author:
  name: Nagesh Podilapu
  email: nagesh.podilapu@gmail.com
  bio: "I love getting lost in information security, software development, and listening music a lot."
  facebook: H4rryp0tt3r7
  twitter: H4rryp0tt3r7
  linkedin: h4rryp0tt3r
  github: H4rryp0tt3r
  country: India
description: > # Sample description for the blog
baseurl: ""
url: "http://nagesh.blog"

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
