title: Your awesome title
email: your-email@domain.com
description: > # Sample discription for the blog
baseurl: ""
url: "http://nagesh.blog"
twitter_username: H4rryp0tt3r7
github_username:  H4rryp0tt3r

disqus:
  shortname: nagesh-blog
google_analytics: UA-89732230-1

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
