title: Eureka
author:
  name: Nagesh Podilapu
  email: nagesh.podilapu@gmail.com
  bio: "I love getting lost in information security, software development, and listening music a lot."
  facebook: H4rryp0tt3r7
  twitter: H4rryp0tt3r7
  linkedin: h4rryp0tt3r
  github: H4rryp0tt3r
  country: India
description: > # Sample discription for the blog
baseurl: ""
url: "https://h4rryp0tt3r.github.io"

google_analytics: UA-89753001-1

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
